### ISSUE TITLE
Autoload of functions fails

### ISSUE THREAD

**Issue by NICHOLAS85** [marlonrichert/zsh-edit#1]
In the plugin I can see `autoload -Uz $fdir/*` is used to autoload the functions used by this plugin. However, on my system it seems the use of an absolute path does not allow the functions to be found when needed. I get a `No such shell function 'edit-subword'` for example. I found if I were to remove the absolute path and simply autoload the functions with their names I could proceed to use the plugin. This is possible because of the earlier fpath modification done. `autoload -Uz _show_clipboard edit-subword visual-yank`

**Comment by marlonrichert** [comment]
@NICHOLAS85 What version of Zsh are you using?

**Comment by marlonrichert** [comment]
@NICHOLAS85 Also, what is the value of `$fdir` for you?

**Comment by NICHOLAS85** [comment]
`$ZSH_VERISON = 5.8`
`$fdir` is `/home/nicholas/.zinit/plugins/marlonrichert---zsh-edit/functions` and the autoload line expands to the following:
`autoload -Uz /home/nicholas/.zinit/plugins/marlonrichert---zsh-edit/functions/edit-subword /home/nicholas/.zinit/plugins/marlonrichert---zsh-edit/functions/_show_clipboard /home/nicholas/.zinit/plugins/marlonrichert---zsh-edit/functions/visual-yank`

**Comment by NICHOLAS85** [comment]
I've used the following in my own config to autoload personal functions, the second line may be of interest:
```zsh
fpath=("${0:h}/functions" "${fpath[@]}")
autoload -Uz $fpath[1]/*(.:t)
```
I've read the docs for autoloading and it seems it should work with an absolute path so I don't know why exactly it isn't in my case, But I'm assuming it does on your machine.

**Comment by marlonrichert** [comment]
@NICHOLAS85 I just noticed you're using Zinit. The problem might actually be there. Can you please try `source`ing the plugin file directly, instead of using Zinit to load it?

**Comment by NICHOLAS85** [comment]
Ah, after resetting the repo and sourcing it instead of using Zinit I find it works correctly. It looks like we'll need to open an issue with Zinit.

**Comment by marlonrichert** [comment]
@NICHOLAS85 May I suggest you switch to using https://github.com/marlonrichert/zsh-snap instead of Zinit? Znap requires less memory and less diskspace, is faster at runtime (because it doesn't do any of the nonsense that Zinit does, some of which you just experienced), and can make your shell start up just as fast, but with way less effort from your side. 🙂

**Comment by NICHOLAS85** [comment]
I have actually looked at your other project https://github.com/marlonrichert/zsh-snap with great interest however I take heavy advantage of the ices Zinit provides to control my configuration. I agree Zinit seems to do a lot and unfortunately suffers from a complicated syntax but now that I've learned it, it'll be hard to switch to other managers which offer less granularity. For now, I'll just have a patch apply the change needed to fix this plugin with Zinit until I have the time to make an issue for Zinit.

Thanks for helping! I'll keep https://github.com/marlonrichert/zsh-snap in mind for future configs

**Comment by marlonrichert** [comment]
What features exactly would you need from Znap to seriously consider switching? Asking for a friend. 😉

**Comment by NICHOLAS85** [comment]
Heres my zshrc for reference: https://github.com/NICHOLAS85/dotfiles/blob/xps_13_9365_refresh/.zshrc
Here some more zsh related files/configuration is done: https://github.com/NICHOLAS85/dotfiles/tree/xps_13_9365_refresh/.zinit/plugins/_local---config-files

I take advantage of many of the ices Zinit offers, and if Znap were to implement them, I believe it'd detract from the lightweight simplicity Znap is advertising. But to answer your question I'll share some of the features I like.
I quite like the [`patch`](https://github.com/zinit-zsh/z-a-patch-dl) ice as it allows me to apply my own fixes/adjustments to plugins which may not be accepted upstream or are configuration specific.
The `blockf` ice simply stops plugins from modifying fpath as Zinit manages it for me.
[`sbin`](https://github.com/zinit-zsh/z-a-bin-gem-node#1-sbingncneopath-to-binary---name-of-the-script-) keeps my $PATH clean.
`ver` lets me checkout a specific branch or commit of a plugin.
`trigger-load` only loads the plugin when a specific command is entered.
`from'gh-r'` lets me download files from github releases.
And of course Zinit allows me to "load" a plugin with tracking so I can keep track of what the plugin did while loading, useful for diagnosing issues.
