### ISSUE TITLE
Missing Install Instructions

### ISSUE THREAD

**Issue by Soromeister** [marlonrichert/zsh-edit#11]
## What do you want?
Please provide installation instructions for vanilla ZSH as well as Oh-My-ZSH

## Why do you want this?
To be able to properly install this

## Who else would benefit from this?
Everyone else who wishes to use this project

## How should it work?

Given this situation:
User reads the README.md

When I perform these steps:
Look for installation instructions

Then I expect this to happen:
Installation instructions should be present and easy to follow

**Comment by iloveitaly** [comment]
@marlonrichert thanks for the instructions on the feature branch! On my machine (ventura, zsh 5.9) I'm running into the following error when I attempt to `C-w`:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/150855/209832933-75d38e19-c4d7-4b1d-a8b5-d0ee860fb12d.png">

It looks like this may be fixed on the feature branch? Would be great to get those changes in master. Thanks for all of your hard work here.
