### ISSUE TITLE
Can you merge the quote fix in dev branch?

### ISSUE THREAD

**Issue by IhsanGunay** [marlonrichert/zsh-edit#15]
## What do you want?

Can you merge the quote fix in dev branch?

## Why do you want this?

Binding commands with arguments doesn't work due to mishandled quotes.

## Who else would benefit from this?

Everyone.
## How should it work?

Given this situation:
* 
*

When I perform these steps:
1. 
1. 

Then I expect this to happen:
* 
*

**Comment by marlonrichert** [comment]
@IhsanGunay Done.
