### ISSUE TITLE
Using bindings results in "No such shell function `.edit.subword'" error

### ISSUE THREAD

**Issue by Jackenmen** [marlonrichert/zsh-edit#17]
## Describe the bug
When trying to use any binding provided by zsh-edit, I run into this error message:
```
No such shell function `.edit.subword'
```
Additionally, it seems that when trying to use zsh-edit on a fresh machine, I'm also seeing (or similar depending on which binding is used):
```
No such widget `.backward-shell-word'
```

## Steps To Reproduce

I reproduced this on a fresh Ubuntu 20.04 VM with `git` and `zsh` packages installed.

1. Put this in `.zshrc`
```zsh
# Created by newuser for 5.8
source ~/zsh-snap/znap.zsh

znap source marlonrichert/zsh-edit
```
2. Open zsh.
3. Use Alt+Left/Right shortcut.
4. See the issue

## Expected behavior
I expected the bindings to move by a shell/subword as it did before.

## Observed behavior

Using the key binding resulted in an error:
```
No such shell function `.edit.subword'
```

## Environment:
 - OS: Ubuntu 20.04 and 22.04
 - Terminal: Gnome Terminal and kitty
 - Zsh version: 5.8 and 5.8.1
 - Repo version: ``* main 98ae841 Update GitHub tests to `ubuntu-latest` ``

## Additional context

The issue seems to have been introduced by https://github.com/marlonrichert/zsh-edit/commit/faf5a1e332cbf7677dadbbc1972a75971dcf8e38

**Comment by QuarticCat** [comment]
Same issue

**Comment by zhouying20** [comment]
`setopt EXTENDED_GLOB`

before sourcing the plugin may help, but the shell-forward/backword are not working as discribed in README....

**Comment by otakutyrant** [comment]
I have just installed this plugin but encountered this issue then.

**Comment by Jackenmen** [comment]
@otakutyrant As a workaround I suggest to figure out how to pin to a git commit in your plugin manager and using the last working commit which is `fcddcbc5ac24643167d47bb34994e4e62a1dbe9e`. That's what I'm doing anyway.

**Comment by QuarticCat** [comment]
For anyone who only needs the subword widget, I wrote a simplified version and fixed a bug by the way.

https://github.com/QuarticCat/dotfiles/blob/76745aee9b2df1cd0d41fc1ece8caf4c2ceb4c85/zsh/.zshrc#L253-L290

It requires `setopt extended_glob`.

**Comment by otakutyrant** [comment]
@Jackenmen This workaround works! Thank you.

**Comment by marlonrichert** [comment]
Sorry about that. It's fixed now.
