### ISSUE TITLE
Insert key is absent from bind

### ISSUE THREAD

**Issue by roadkell** [marlonrichert/zsh-edit#20]
## Describe the bug
<kbd>Insert</kbd> key is absent from `functions/bind`.

## Steps To Reproduce
Any `bind` command involving <kbd>Insert</kbd> key (`^[[2~`).

## Expected behavior
```
❯ bind -n '^[[2~'
"^[[2~"   Insert

❯ bind -n '^[[2;2~'
"^[[2;2~"   Shift-Insert
```
etc.

## Observed behavior
```
❯ bind -n '^[[2~'
"^[[2~"   Shift-

❯ bind -n '^[[2;2~'
"^[[2;2~"   Alt-[ + 2 + ; + 2 + ~
```
etc.

</details>

## Environment:
 - OS: Pop!_OS 22.04 LTS x86_64
 - Terminal: kitty 0.24.1
 - Zsh version: 5.8.1
 - Repo version: * main 9eb2869 Don't overwrite Autosuggest's default ignore list

## Additional context

Seems to be fairly simple to fix (add `( '[2;' ) name+='Insert'` to the case-matches). Should i make a PR?
(I'm just not sure what does `1` mean [here](https://github.com/marlonrichert/zsh-edit/blob/9eb286982f96f03371488e910e42afb23802bdfd/functions/bind#L53C30-L53C31). Is this a typo? Also, all the regex magic in `bind` is so awesome it blows my mind).

**Comment by marlonrichert** [comment]
> Should i make a PR?

That would be nice. 🙂 

> I'm just not sure what does `1` mean [here](https://github.com/marlonrichert/zsh-edit/blob/9eb286982f96f03371488e910e42afb23802bdfd/functions/bind#L53C30-L53C31). Is this a typo?

No, not a typo. For example:
```
% bind -n "^[[1;2A"
"^[[1;2A"   Shift-Up
%
```

> Also, all the regex magic in `bind` is so awesome it blows my mind.

It's not regex. They're [glob patterns](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Filename-Generation). 🙂

**Comment by roadkell** [comment]
Oh, now it makes sense, thanks. )

Hmm, but shouldn't there be `ABCDFHZ` instead of `ABCDFH` [here](https://github.com/marlonrichert/zsh-edit/blob/9eb286982f96f03371488e910e42afb23802bdfd/functions/bind#L35C28-L35C34), and `F` instead of `E` [here](https://github.com/marlonrichert/zsh-edit/blob/9eb286982f96f03371488e910e42afb23802bdfd/functions/bind#L41C15-L41C16)? At least, it seems to work if fixed:
```
❯ bind -n '^[[F'
"^[[F"   End
❯ bind -n '^[[Z'
"^[[Z"   Shift-Tab
```
while the current version doesn't:
```
❯ bind -n '^[[F'
"^[[F"
❯ bind -n '^[[Z'
"^[[Z"   Alt-[ + Shift-Z
```

**Comment by marlonrichert** [comment]
Good catch. Thanks! I've now fixed it.

**Comment by roadkell** [comment]
Nice! Now, about that `Insert` key thing... )
