### ISSUE TITLE
Hide command output?

### ISSUE THREAD

**Issue by drewauff** [marlonrichert/zsh-edit#5]
How do I hide the output of Keybindings shortcut?

ie. ctrl+[ to go back a directory, when I hit ctrl+[ it displays cd .. then runs it, how do I hide this ?

**Comment by marlonrichert** [comment]
Sorry, that's not possible—or at least, not in a way that doesn't potentially screw up your prompt. Such functionality would be possible to implement as part of your prompt, but that's out of scope for this plugin.

**Comment by marlonrichert** [comment]
I discovered that there might be a way to do this, after all.

**Comment by drewauff** [comment]
good to hear :)

**Comment by marlonrichert** [comment]
All right, it's there now. 🙂 Please see the [Readme](https://github.com/marlonrichert/zsh-edit/blob/main/README.md#bindkey-extensions) for more info.
