### ISSUE TITLE
bind:zparseopts:10: no default array defined: -F

### ISSUE THREAD

**Issue by adamshand** [marlonrichert/zsh-edit#7]
I upgraded to the latest version of zsh-edit a few days ago and since then I've been getting this error when a new zsh opens:

```
bind:zparseopts:10: no default array defined: -F
bind:zparseopts:10: no default array defined: -F
```

It doesn't seem to error on computers with zsh 5.8 but on my Debian server running 5.7.1-1 I get the above error.  Not sure if that's coincidence or not.

**Comment by marlonrichert** [comment]
Fixed.

---

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
