### ISSUE TITLE
Recent change removed `backward-kill-subword` functionality

### ISSUE THREAD

**Issue by cjk** [marlonrichert/zsh-edit#9]
After updating zsh-init the other week, suddently `Alt-Backspace` kills backwards to next space always.

It used to kill only `$WORDCHARS` like:

`ls /my/path/here` became `ls /my/path`

...but now it kills the whole (second) argument and only `ls` remains - which is not very convenient in most situations.

I checked the code but was unable to locate the specific change that caused this.

**Comment by marlonrichert** [comment]
That’s [according to spec](https://github.com/marlonrichert/zsh-edit#key-bindings). It changed in 0b6eb420f90d737b43379c243084c19f4c747a83.

<kbd>Alt</kbd><kbd>Backspace</kbd> is bound to `backward-kill-shell-word`. For `backward-kill-subword`, press <kbd>Ctrl</kbd><kbd>Backspace</kbd> or <kbd>Ctrl</kbd><kbd>H</kbd>.

Having said that, though, it’s trivial enough to change <kbd>Alt</kbd><kbd>Backspace</kbd> to `backward-kill-subword`. Just add to your `.zshrc` file, _after_ sourcing `zsh-edit`:
   ```zsh
   bindkey '^[^?' backward-kill-subword
   ```

**Comment by marlonrichert** [comment]
<kbd>Alt</kbd><kbd>Backspace</kbd> is back to `backward-kill-subword`! 😀  

I did some more thinking and decided that it wasn't the best idea to move that key binding. Instead, I have now added many alternative key bindings, to make Zsh-Edit usable on more terminal emulators.

See https://github.com/marlonrichert/zsh-edit/blob/main/README.md#key-bindings for the full list.

**Comment by cjk** [comment]
Thanks, appreciated! Now my zsh-config can go back to simple again :wink:

**Comment by marlonrichert** [comment]
You're welcome! 🙂

---

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 💝
